services:
  - type: web
    name: whatsapp-service
    runtime: node
    buildCommand: bash render-build.sh
    startCommand: node index.js
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: SESSION_DATA_PATH
        value: /opt/render/project/src/sessions
      - key: PORT
        value: "5000"
      - key: ASP_NET_BASE_URL
        sync: false
      - key: NODE_TOKEN
        sync: false
      - key: SERVER_NAME
        value: NODE_WHATSAPP_SERVICE
    disk:
      name: whatsapp-sessions
      mountPath: /opt/render/project/src/sessions
      sizeGB: 1
